// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkDlTX7MMHA-9PnMesasPAF0w_rtuUzJk',
    appId: '1:61624601401:android:7d7f918acdab8319baf6e8',
    messagingSenderId: '61624601401',
    projectId: 'corsoflutterterzalezione',
    databaseURL: 'https://corsoflutterterzalezione-default-rtdb.firebaseio.com',
    storageBucket: 'corsoflutterterzalezione.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_-uRytbSSXFcLViwX4-VXfJ_zTSgQ49k',
    appId: '1:61624601401:ios:16a0b0af043f9ff7baf6e8',
    messagingSenderId: '61624601401',
    projectId: 'corsoflutterterzalezione',
    databaseURL: 'https://corsoflutterterzalezione-default-rtdb.firebaseio.com',
    storageBucket: 'corsoflutterterzalezione.appspot.com',
    androidClientId: '61624601401-15lrmrg4bb2mib1o828c4bfofdkgld2d.apps.googleusercontent.com',
    iosClientId: '61624601401-5phl0ld7cavi11mbqd7fh40vd42ngkgp.apps.googleusercontent.com',
    iosBundleId: 'com.iisrl.corsoBaseFlutterAlberto',
  );
}
